name: rickandmorty
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  dio: 4.0.0
  equatable:
  bloc: 7.0.0
  flutter_bloc: 7.0.0
  shimmer: 2.0.0
  cached_network_image: 3.0.0
  flutter_cache_manager: 3.1.2
  get_it: 6.0.0
  shared_preferences: 2.0.6

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  effective_dart: 1.3.2
  mocktail: 0.1.4
  bloc_test: 8.0.0

flutter:
  uses-material-design: true
